# Generated by Django 3.2.5 on 2021-07-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(db_index=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
                ('high_thumbnail', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('published_at', models.DateTimeField()),
                ('default_thumbnail', models.CharField(blank=True, max_length=250, null=True)),
                ('medium_thumbnail', models.CharField(blank=True, max_length=250, null=True)),
                ('channel_id', models.CharField(db_index=True, max_length=100, null=True)),
                ('channel_title', models.CharField(db_index=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
