# Generated by Django 3.2.5 on 2021-07-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeSearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubeapikey',
            old_name='secret',
            new_name='api_key',
        ),
    ]
