# Generated by Django 3.2.5 on 2021-07-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeSearch', '0002_rename_secret_youtubeapikey_api_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubeapikey',
            old_name='updatedAt',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_video_id',
            field=models.CharField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('title', 'youtube_video_id')},
        ),
    ]
